### ISSUE TITLE
Flagged as virus

### ISSUE THREAD

**Issue by mattmoody05** [phaselden/FlipIt#16]
I have complete confidence that this project is not a virus, but windows10 is convinced that it is. 
I have downloaded the Flipit.scr file from the 1.3 release and windows has flagged it as a virus. Not sure if this is anything you can solve, but I thought it would be good for you to know.
Still, looks awesome :)
![image](https://user-images.githubusercontent.com/34244370/107568925-9bc21900-6bdf-11eb-83cf-959d6ef6f3fb.png)

**Comment by SmilerRyan** [comment]
I have re-scanned this file on VirusTotal ([Results are here](https://www.virustotal.com/gui/file/ae9c2434eaa38183c4957ed356542fd74401557e4a9f3ad1947fb0158b5babcd/detection)) and it appears not to be detected by any engine, including Microsoft. Is this the only AntiVirus engine you use?

**Comment by mattmoody05** [comment]
Hi, sorry to take more of your time. Here is the Windows Security "Threat blocked" info
![image](https://user-images.githubusercontent.com/34244370/107572179-d29a2e00-6be3-11eb-9e37-2a8cabfaa413.png)

**Comment by edeao** [comment]
Hi community, dear developer,

THX for the great work!!
I am also completly confident that this is not a virus, but Win10  version 20H2 thinks otherwise.
I also attachted a screenshot. Screensaver was running perfect for two days, than windows blocked it.
I had to unblock it, even to download it. Copied it in the folder again an now it works just fine again.

![Unbenannt](https://user-images.githubusercontent.com/78914226/107644637-fad36c80-6c77-11eb-9325-31eb6902396b.jpg)

Hope you can fix this issue and thanks again for the great work. Hope you get the recognition you derserve!!

**Comment by redburn** [comment]
I don't get the virus alert myself on Windows 10, but have nevertheless reported it to Microsoft as a false positive.

Usually they'll clear it within 24 hours.

**Comment by redburn** [comment]
> Analyst comments:
> 
> We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.
> 
> 1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
> 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> 3. Run "MpCmdRun.exe -SignatureUpdate"
> 
> Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions
