### ISSUE TITLE
Multi monitor not working correctly

### ISSUE THREAD

**Issue by dvpetta** [phaselden/FlipIt#21]
Hey everyone, 

I have loaded this onto my windows 10 laptop and having odd results, or at least not the same as what the "test" function does.  Here is a picture of what I'm seeing across my three screens:

https://imgur.com/a/tTvjlVb

Any ideas on how to fix this or any additional information that is needed?
Daniel

**Comment by phaselden** [comment]
Hi Daniel. 

That screen is not FlipIt. By that I mean that there is nothing in the code that will draw the time like that. Also I am not sure that that is actually a screen saver since the Windows Taskbar is being shown on the other monitors. 

Can you check that FlipIt is selected as the current screen saver in the Screen Saver Settings dialog?

**Comment by dvpetta** [comment]
Hey @phaselden , sorry about the confusion, I had forgotten I had installed another screensaver that was causing the issue.  I was able to install Flipit no problem!  Thanks for your help.

Daniel
